"""Demo data for testing the penny bot without API access."""

from scanner import PennyOpportunity

DEMO_MARKETS = [
    PennyOpportunity(
        market_question="Will Elon Musk post 200-279 tweets this week?",
        market_slug="elon-musk-tweets-200-279",
        token_id="demo_token_musk_200_279",
        outcome="YES",
        price=0.04,
        condition_id="demo_cond_1",
        end_date="2026-02-10T00:00:00Z",
    ),
    PennyOpportunity(
        market_question="Will Elon Musk post 280-359 tweets this week?",
        market_slug="elon-musk-tweets-280-359",
        token_id="demo_token_musk_280_359",
        outcome="YES",
        price=0.07,
        condition_id="demo_cond_2",
        end_date="2026-02-10T00:00:00Z",
    ),
    PennyOpportunity(
        market_question="Will Elon Musk post 360-439 tweets this week?",
        market_slug="elon-musk-tweets-360-439",
        token_id="demo_token_musk_360_439",
        outcome="YES",
        price=0.03,
        condition_id="demo_cond_3",
        end_date="2026-02-10T00:00:00Z",
    ),
    PennyOpportunity(
        market_question="Will Elon Musk post 440-519 tweets this week?",
        market_slug="elon-musk-tweets-440-519",
        token_id="demo_token_musk_440_519",
        outcome="YES",
        price=0.02,
        condition_id="demo_cond_4",
        end_date="2026-02-10T00:00:00Z",
    ),
    PennyOpportunity(
        market_question="Will Elon Musk post 520+ tweets this week?",
        market_slug="elon-musk-tweets-520-plus",
        token_id="demo_token_musk_520",
        outcome="YES",
        price=0.01,
        condition_id="demo_cond_5",
        end_date="2026-02-10T00:00:00Z",
    ),
    PennyOpportunity(
        market_question="Will BTC be above $120,000 on February 14?",
        market_slug="btc-above-120k-feb14",
        token_id="demo_token_btc_120k",
        outcome="YES",
        price=0.05,
        condition_id="demo_cond_6",
        end_date="2026-02-14T00:00:00Z",
    ),
    PennyOpportunity(
        market_question="Will Tesla announce new product before March 2026?",
        market_slug="tesla-new-product-march",
        token_id="demo_token_tesla",
        outcome="YES",
        price=0.08,
        condition_id="demo_cond_7",
        end_date="2026-03-01T00:00:00Z",
    ),
    PennyOpportunity(
        market_question="Will there be a government shutdown in February 2026?",
        market_slug="govt-shutdown-feb",
        token_id="demo_token_shutdown",
        outcome="YES",
        price=0.06,
        condition_id="demo_cond_8",
        end_date="2026-02-28T00:00:00Z",
    ),
    PennyOpportunity(
        market_question="Will SpaceX Starship complete orbital flight in February?",
        market_slug="spacex-orbital-feb",
        token_id="demo_token_spacex",
        outcome="YES",
        price=0.09,
        condition_id="demo_cond_9",
        end_date="2026-02-28T00:00:00Z",
    ),
    PennyOpportunity(
        market_question="Will ETH flip BTC in market cap by March 2026?",
        market_slug="eth-flip-btc-march",
        token_id="demo_token_ethflip",
        outcome="YES",
        price=0.01,
        condition_id="demo_cond_10",
        end_date="2026-03-01T00:00:00Z",
    ),
]
